# See https://github.com/kentaro-m/auto-assign-action/pull/23/files#r468249895
on:
    pull_request:
      types: [opened]

jobs:
  add-reviews:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.1.2
        with:
          configuration-path: ".github/auto_assign.yml" 