name: Publish Packages

on:
  workflow_dispatch:

jobs:
  publish-to-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v2
        with:
          # pulls all commits and tags (needed for lerna / semantic release to correctly version)
          fetch-depth: 0

      - name: Check that we're on master
        if: github.ref != 'refs/heads/master'
        run: exit 1

      - uses: actions/setup-node@v1
        with:
          node-version: 12.16.3

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-yarn-cache-v2-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-cache-v2-

      - name: yarn install
        # skip the prepare step here, as lerna publish will run prepare before publishing
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
          SKIP_PREPARE=true yarn install

      - name: Configure CI Git User
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"

      - name: publish packages to npm
        run: |
          yarn run lerna version --conventional-commits --yes --exact --no-push --message "chore(release): publish [skip ci]"
          yarn run lerna publish from-git --yes

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: update-master-with-published-versions
          title: Updates published versions [please merge ASAP]
          body: Updates to the versions and changelogs created by the `Publish Packages` action

      - name: push commit tags
        run: git push --tags
